# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Txorua Web Design
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.txoruawebdesign.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: igarbla
github_username:  igarbla

# Build settings
markdown: kramdown
languages: ['es']
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-pwa-plugin
remote_theme: Txorua/twd-jt-simple

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - README.md
 - Gemfile
 - Gemfile.lock
 - package.json
 - package-lock.json
 - gulpfile.js
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/

collections_dir: content
collections:
  pages:
    output: true
  banners:
  trabajos:

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:title

## PWA
pwa:
  sw_filename: sw.js
  dest_js_directory: js
  cache_name: txorua-web-design-pwa
  precache_recent_posts_num: 12
  precache_glob_directory: /
  precache_glob_patterns:
    - "{js,css,fonts}/**/*.{js,css,woff,woff2}"
    - /index.html
    - /about.html
  precache_glob_ignores:
    - sw-register.js
  runtime_cache:
    - route: /^api\/getdata/
      strategy: networkFirst
    - route: "'/api/pic'"
      strategy: cacheFirst
